apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skillcrm-storage
  namespace: twentycrm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
