apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skillcrm-stage-storage
  namespace: twentycrm-stage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
