name: 'Send Telegram Notification'
description: 'Send notification to Telegram about deployment status'
inputs:
  status_emoji:
    description: 'Emoji for status (e.g., ❌, ✅, 🚀)'
    required: false
    default: '❌'
  status_text:
    description: 'Status text (e.g., "Ошибка", "Успешно")'
    required: true
  details:
    description: 'Additional details about the error or success'
    required: false
    default: 'Нет дополнительной информации'
  step_name:
    description: 'Name of the step that failed/succeeded'
    required: false
    default: 'Неизвестный шаг'
  image_tag:
    description: 'Docker image tag'
    required: false
    default: 'unknown'
  environment:
    description: 'Environment name'
    required: false
    default: 'stage'
  domain:
    description: 'Domain name'
    required: false
    default: 'stage.skillcrm.ru'
  bot_token:
    description: 'Telegram bot token (pass from workflow secrets)'
    required: true
  chat_id:
    description: 'Telegram chat id (pass from workflow secrets)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Telegram Message
      shell: bash
      run: |
        # Отладочная информация
        echo "🔍 Debug Telegram notification:"
        echo "Bot token set: $([[ -n "${{ inputs.bot_token }}" ]] && echo "YES" || echo "NO")"
        echo "Chat ID set: $([[ -n "${{ inputs.chat_id }}" ]] && echo "YES" || echo "NO")"
        echo "Status emoji: ${{ inputs.status_emoji }}"
        echo "Status text: ${{ inputs.status_text }}"
        echo "Environment: ${{ inputs.environment }}"
        echo "Domain: ${{ inputs.domain }}"
        echo "Image tag: ${{ inputs.image_tag }}"
        
        # Формируем сообщение
        MESSAGE="${{ inputs.status_emoji }} *${{ inputs.status_text }}!*"
        MESSAGE="${MESSAGE}\n\n🌍 *Окружение:* ${{ inputs.environment }}"
        MESSAGE="${MESSAGE}\n🌐 *Домен:* https://${{ inputs.domain }}"
        MESSAGE="${MESSAGE}\n🐳 *Образ:* \`${{ inputs.image_tag }}\`"
        MESSAGE="${MESSAGE}\n📝 *Коммит:* \`${{ github.sha }}\`"
        MESSAGE="${MESSAGE}\n👤 *Автор:* ${{ github.actor }}"
        MESSAGE="${MESSAGE}\n⏰ *Время:* $(date '+%d.%m.%Y %H:%M:%S')"
        MESSAGE="${MESSAGE}\n\n🔍 *Детали:* ${{ inputs.details }}"
        
        echo "📤 Sending message to Telegram..."
        
        # Отправляем сообщение в Telegram
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://api.telegram.org/bot${{ inputs.bot_token }}/sendMessage" \
          -d chat_id="${{ inputs.chat_id }}" \
          -d text="$MESSAGE" \
          -d parse_mode="Markdown" \
          -d disable_web_page_preview=true)
        
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
        
        echo "📡 Telegram API Response:"
        echo "HTTP Code: $HTTP_CODE"
        echo "Response Body: $RESPONSE_BODY"
        
        if [ "$HTTP_CODE" = "200" ]; then
          echo "✅ Telegram message sent successfully!"
        else
          echo "❌ Failed to send Telegram message. HTTP Code: $HTTP_CODE"
          echo "Response: $RESPONSE_BODY"
          exit 1
        fi
