name: Deploy to Kubernetes Stage Environment

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deploy even if no changes'
        required: false
        default: false
        type: boolean

env:
  DOCKER_REGISTRY: skillcrm-register.registry.twcstorage.ru
  DOCKER_IMAGE_NAME: twenty
  ENVIRONMENT: stage
  DOMAIN: stage.skillcrm.ru

jobs:
  build-and-deploy:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug Registry Info
        run: |
          echo "Registry: ${{ env.DOCKER_REGISTRY }}"
          echo "Username: ${{ secrets.DOCKER_REGISTRY_USER }}"
          echo "Token length: ${#DOCKER_REGISTRY_TOKEN}"
          echo "Token starts with: ${DOCKER_REGISTRY_TOKEN:0:20}..."
          echo "Available secrets:"
          env | grep -E "(DOCKER|REGISTRY)" | head -10

      - name: Login to Docker Registry
        id: registry-login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Notify Telegram - Registry Login Failed
        if: failure() && steps.registry-login.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Ошибка входа в Docker Registry"
          details: "Проверьте DOCKER_REGISTRY_USER и DOCKER_REGISTRY_TOKEN"
          step_name: "Registry Login"
          image_tag: "unknown"
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=stage,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/twenty-docker/twenty/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REACT_APP_SERVER_BASE_URL=https://${{ env.DOMAIN }}
            APP_VERSION=${{ github.sha }}

      - name: Notify Telegram - Docker Build Failed
        if: failure() && steps.build-push.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Ошибка сборки Docker образа"
          details: "Проверьте Dockerfile и зависимости"
          step_name: "Docker Build"
          image_tag: "unknown"
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        id: configure-kubectl
        run: |
          # Configure kubectl for your Kubernetes cluster
          # Create kubeconfig directory
          mkdir -p ~/.kube
          
          # Write kubeconfig from secret
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          
          # Set proper permissions
          chmod 600 ~/.kube/config
          
          # Verify connection
          kubectl cluster-info

      - name: Notify Telegram - kubectl Configuration Failed
        if: failure() && steps.configure-kubectl.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Ошибка настройки kubectl"
          details: "Проверьте KUBECONFIG секрет и доступ к кластеру"
          step_name: "kubectl Configuration"
          image_tag: "unknown"
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}

      - name: Deploy to Kubernetes Stage
        id: deploy-k8s
        run: |
          cd packages/twenty-docker/k8s
          export DOCKER_REGISTRY_USER=${{ secrets.DOCKER_REGISTRY_USER }}
          export DOCKER_REGISTRY_TOKEN=${{ secrets.DOCKER_REGISTRY_TOKEN }}
          # Берем только первый тег из списка
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d' ' -f1)
          export IMAGE_TAG
          echo "Deploying with image: $IMAGE_TAG"
          ./deploy.sh stage "$IMAGE_TAG"

      - name: Notify Telegram - Kubernetes Deployment Failed
        if: failure() && steps.deploy-k8s.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Ошибка развертывания в Kubernetes"
          details: "Проверьте манифесты Kubernetes и права доступа"
          step_name: "Kubernetes Deployment"
          image_tag: ${{ steps.meta.outputs.tags }}
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}

      - name: Health Check
        id: health-check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          for i in {1..10}; do
            if curl -f https://${{ env.DOMAIN }}/healthz; then
              echo "✅ Stage deployment successful!"
              exit 0
            fi
            echo "Waiting for health check... ($i/10)"
            sleep 30
          done
          echo "❌ Health check failed"
          exit 1

      - name: Notify Telegram - Health Check Failed
        if: failure() && steps.health-check.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Health Check не прошел"
          details: "Приложение не отвечает на health check"
          step_name: "Health Check"
          image_tag: ${{ steps.meta.outputs.tags }}
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}

      - name: Notify Telegram - Final Status
        if: always()
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: ${{ job.status == 'success' && '🚀' || '❌' }}
          status_text: ${{ job.status == 'success' && 'Деплой успешно завершен' || 'Деплой завершился с ошибкой' }}
          details: ${{ job.status == 'success' && 'Все шаги выполнены успешно' || 'Проверьте логи для деталей' }}
          step_name: "Final Status"
          image_tag: ${{ steps.meta.outputs.tags }}
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}
