name: Deploy to Kubernetes Stage Environment

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deploy even if no changes'
        required: false
        default: false
        type: boolean

env:
  DOCKER_REGISTRY: skillcrm-register.registry.twcstorage.ru
  DOCKER_IMAGE_NAME: twenty
  ENVIRONMENT: stage
  DOMAIN: stage.skillcrm.ru

concurrency:
  group: deploy-stage-develop
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        id: registry-login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Notify Telegram - Registry Login Failed
        if: failure() && steps.registry-login.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Ошибка входа в Docker Registry"
          details: "Проверьте DOCKER_REGISTRY_USER и DOCKER_REGISTRY_TOKEN"
          step_name: "Registry Login"
          image_tag: "unknown"
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=ref,event=branch

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/twenty-docker/twenty/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            REACT_APP_SERVER_BASE_URL=https://${{ env.DOMAIN }}
            APP_VERSION=${{ github.sha }}

      - name: Notify Telegram - Docker Build Failed
        if: failure() && steps.build-push.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Ошибка сборки Docker образа"
          details: "Проверьте Dockerfile и зависимости"
          step_name: "Docker Build"
          image_tag: "unknown"
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.4'

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          yc --version

      - name: Configure Yandex Cloud auth
        env:
          YC_SA_KEY_JSON: ${{ secrets.YC_SA_KEY_JSON }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
        run: |
          if [ -z "$YC_SA_KEY_JSON" ] || [ -z "$YC_CLOUD_ID" ] || [ -z "$YC_FOLDER_ID" ]; then
            echo "YC credentials are not provided via secrets (YC_SA_KEY_JSON/YC_CLOUD_ID/YC_FOLDER_ID)." >&2
            echo "If your kubeconfig uses 'exec' with yc, these are required." >&2
          else
            echo "$YC_SA_KEY_JSON" > sa-key.json
            yc config profile create ci-profile || true
            yc config set service-account-key sa-key.json
            yc config set cloud-id "$YC_CLOUD_ID"
            yc config set folder-id "$YC_FOLDER_ID"
            yc config list
          fi

      - name: Configure kubectl
        id: configure-kubectl
        env:
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          KUBE_CA_DATA: ${{ secrets.KUBE_CA_DATA }}
          KUBE_BEARER_TOKEN: ${{ secrets.KUBE_BEARER_TOKEN }}
          KUBECONFIG_SECRET: ${{ secrets.KUBECONFIG }}
        run: |
          # Configure kubectl for your Kubernetes cluster
          mkdir -p ~/.kube
          # Prefer static kubeconfig if provided
          if [ -n "$KUBE_SERVER" ] && [ -n "$KUBE_CA_DATA" ] && [ -n "$KUBE_BEARER_TOKEN" ]; then
            # Build kubeconfig via kubectl config commands (avoids heredoc YAML in workflow)
            : > ~/.kube/config
            kubectl config set-cluster yc-cluster --server="$KUBE_SERVER"
            kubectl config set clusters.yc-cluster.certificate-authority-data "$KUBE_CA_DATA"
            kubectl config set-credentials sa-user --token="$KUBE_BEARER_TOKEN"
            kubectl config set-context yc-context --cluster=yc-cluster --user=sa-user
            kubectl config use-context yc-context
            chmod 600 ~/.kube/config
            kubectl cluster-info
            exit 0
          fi
          tmpcfg="$(mktemp)"
          # Save secret raw
          printf "%s" "$KUBECONFIG_SECRET" > "$tmpcfg"
          # Try base64 decode first
          if base64 -d "$tmpcfg" > "$tmpcfg.dec" 2>/dev/null; then
            if head -n1 "$tmpcfg.dec" | grep -Eq '^(apiVersion:|\{)'; then
              mv "$tmpcfg.dec" ~/.kube/config
            else
              rm -f "$tmpcfg.dec"
            fi
          fi
          # If not written yet, interpret escaped newlines (\n)
          if [ ! -f ~/.kube/config ]; then
            printf "%b" "$(cat "$tmpcfg")" > ~/.kube/config
          fi
          rm -f "$tmpcfg"
          chmod 600 ~/.kube/config
          # Normalize YC CLI exec path if present
          if grep -q "exec:" -n ~/.kube/config; then
            sed -i 's|/Users/.*/yandex-cloud/bin/yc|yc|g' ~/.kube/config || true
            sed -i 's|/home/.*/yandex-cloud/bin/yc|yc|g' ~/.kube/config || true
          fi
          # Verify connection
          kubectl cluster-info

      - name: Notify Telegram - kubectl Configuration Failed
        if: failure() && steps.configure-kubectl.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Ошибка настройки kubectl"
          details: "Проверьте KUBECONFIG секрет и доступ к кластеру"
          step_name: "kubectl Configuration"
          image_tag: "unknown"
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Deploy to Kubernetes Stage
        id: deploy-k8s
        run: |
          cd packages/twenty-docker/k8s
          export DOCKER_REGISTRY_USER=${{ secrets.DOCKER_REGISTRY_USER }}
          export DOCKER_REGISTRY_TOKEN=${{ secrets.DOCKER_REGISTRY_TOKEN }}
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | tr ' ' '\n' | grep -E ':[0-9a-f]{7,}$' | head -1 || true)
          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | awk '{print $1}')
          fi
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "Deploying with image: $IMAGE_TAG"
          ./deploy.sh stage "$IMAGE_TAG"

      - name: Notify Telegram - Kubernetes Deployment Failed
        if: failure() && steps.deploy-k8s.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Ошибка развертывания в Kubernetes"
          details: "Проверьте манифесты Kubernetes и права доступа"
          step_name: "Kubernetes Deployment"
          image_tag: ${{ steps.deploy-k8s.outputs.image_tag }}
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Health Check
        id: health-check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          for i in {1..15}; do
            if curl -fsS --connect-timeout 10 --max-time 15 https://${{ env.DOMAIN }}/healthz; then
              echo "✅ Stage deployment successful!"
              exit 0
            fi
            echo "Waiting for health check... ($i/15)"
            sleep 20
          done
          echo "❌ Health check failed"
          exit 1

      - name: Notify Telegram - Health Check Failed
        if: failure() && steps.health-check.outcome == 'failure'
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: "❌"
          status_text: "Health Check не прошел"
          details: "Приложение не отвечает на health check"
          step_name: "Health Check"
          image_tag: ${{ steps.deploy-k8s.outputs.image_tag }}
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Notify Telegram - Final Status
        if: always()
        uses: ./.github/actions/telegram-notify
        with:
          status_emoji: ${{ job.status == 'success' && '🚀' || '❌' }}
          status_text: ${{ job.status == 'success' && 'Деплой успешно завершен' || 'Деплой завершился с ошибкой' }}
          details: ${{ job.status == 'success' && 'Все шаги выполнены успешно' || 'Проверьте логи для деталей' }}
          step_name: "Final Status"
          image_tag: ${{ steps.deploy-k8s.outputs.image_tag }}
          environment: ${{ env.ENVIRONMENT }}
          domain: ${{ env.DOMAIN }}
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
